{{- if .Values.server.enabled }}
{{- range .Values.server.instances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: iperf3-server
        image: "{{ $.Values.image.serverRepository }}:{{ $.Values.image.tag }}"
        env:
        - name: SERVER_PORT
          value: "{{ $.Values.server.containerPort }}"
        ports:
        - containerPort: {{ $.Values.server.containerPort }}
---          
{{- end }}
{{- end }}

