{{- if .Values.client.enabled }}
{{- range $index, $value := .Values.client.serverPorts }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client-{{ $index | add 1 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-client-{{ $index | add 1 }}
  template:
    metadata:
      labels:
        app: iperf3-client-{{ $index | add 1 }}
    spec:
      containers:
      - name: iperf3-client
        image: "{{ $.Values.image.clientRepository }}:{{ $.Values.image.tag }}"
        env:
        - name: CUSTOMER_PORT
          value: "{{ $value }}"
        - name: CUSTOMER_NUMBER_OF_FLOWS
          value: "{{ $.Values.client.flows }}"
        - name: CUSTOMER_TIME_SECONDS
          value: "{{ $.Values.client.duration }}"
        args:
        - /bin/sh
        - -c
        - |
          while true; do
            iperf3 -c {{ index $.Values.client.serverIPs $index }} -p $CUSTOMER_PORT -P $CUSTOMER_NUMBER_OF_FLOWS -t $CUSTOMER_TIME_SECONDS;
            sleep 10;
          done
---
{{- end }}
{{- end }}

