{{- if .Values.server.enabled }}
{{- range .Values.server.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: NodePort
  selector:
    app: {{ .name }}
  ports:
  - protocol: TCP
    port: {{ $.Values.server.containerPort }}
    targetPort: {{ $.Values.server.containerPort }}
    nodePort: {{ .port }}
---      
{{- end }}
{{- end }}

