image:
  clientRepository: iperf3-client
  serverRepository: iperf3-server
  tag: 0.1a
  pullPolicy: IfNotPresent

server:
  enabled: true
  instances:
    - name: iperf3-server-1
      port: 30001
    - name: iperf3-server-2
      port: 30002
    - name: iperf3-server-3
      port: 30003
    - name: iperf3-server-4
      port: 30004
    - name: iperf3-server-5
      port: 30005
    - name: iperf3-server-6
      port: 30006
    - name: iperf3-server-7
      port: 30007
    - name: iperf3-server-8
      port: 30008
    - name: iperf3-server-9
      port: 30009
    - name: iperf3-server-10
      port: 30010
    - name: iperf3-server-11
      port: 30011
    - name: iperf3-server-12
      port: 30012
  containerPort: 5201

client:
  enabled: true
  replicas: 12
  flows: 4
  duration: 0  # 0 means run indefinitely
  serverIPs:
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
    - 172.254.102.101
  serverPorts:
    - 30001
    - 30002
    - 30003
    - 30004
    - 30005
    - 30006
    - 30007
    - 30008
    - 30009
    - 30010
    - 30011
    - 30012

