# Global settings
image:
  serverRepository: iperf3-server  # Image name for the server
  clientRepository: iperf3-client  # Image name for the client
  tag: 0.1a
  pullPolicy: IfNotPresent  # Local images don't require pulling

# Server configuration
server:
  enabled: false  # Enable client deployment
  instances:
    - name: iperf3-server-1
      port: 30001
    - name: iperf3-server-2
      port: 30002
    - name: iperf3-server-3
      port: 30003
    - name: iperf3-server-4
      port: 30004
  containerPort: 5201

# Client configuration
client:
  enabled: true  # Enable client deployment
  replicas: 4
  flows: 4
  duration: 0  # 0 means run indefinitely
  serverIPs:
    - 172.254.102.101  # The node IP where the servers are running
    - 172.254.102.101  # Repeated for each client connection
    - 172.254.102.101
    - 172.254.102.101
  serverPorts:
    - 30001  # Port for client 1
    - 30002  # Port for client 2
    - 30003  # Port for client 3
    - 30004  # Port for client 4
    
